#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterThePlants
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="testdb")]
	public partial class dbContectionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPlant(Plant instance);
    partial void UpdatePlant(Plant instance);
    partial void DeletePlant(Plant instance);
    #endregion
		
		public dbContectionDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["testdbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbContectionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbContectionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbContectionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbContectionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Plant> Plants
		{
			get
			{
				return this.GetTable<Plant>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Plants")]
	public partial class Plant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PlantID;
		
		private string _PlantName;
		
		private System.Nullable<char> _Status;
		
		private System.Nullable<System.DateTime> _LastCompleted;
		
		private System.Nullable<System.DateTime> _Reset;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPlantIDChanging(int value);
    partial void OnPlantIDChanged();
    partial void OnPlantNameChanging(string value);
    partial void OnPlantNameChanged();
    partial void OnStatusChanging(System.Nullable<char> value);
    partial void OnStatusChanged();
    partial void OnLastCompletedChanging(System.Nullable<System.DateTime> value);
    partial void OnLastCompletedChanged();
    partial void OnResetChanging(System.Nullable<System.DateTime> value);
    partial void OnResetChanged();
    #endregion
		
		public Plant()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlantID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PlantID
		{
			get
			{
				return this._PlantID;
			}
			set
			{
				if ((this._PlantID != value))
				{
					this.OnPlantIDChanging(value);
					this.SendPropertyChanging();
					this._PlantID = value;
					this.SendPropertyChanged("PlantID");
					this.OnPlantIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlantName", DbType="VarChar(50)")]
		public string PlantName
		{
			get
			{
				return this._PlantName;
			}
			set
			{
				if ((this._PlantName != value))
				{
					this.OnPlantNameChanging(value);
					this.SendPropertyChanging();
					this._PlantName = value;
					this.SendPropertyChanged("PlantName");
					this.OnPlantNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Char(1)")]
		public System.Nullable<char> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastCompleted", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastCompleted
		{
			get
			{
				return this._LastCompleted;
			}
			set
			{
				if ((this._LastCompleted != value))
				{
					this.OnLastCompletedChanging(value);
					this.SendPropertyChanging();
					this._LastCompleted = value;
					this.SendPropertyChanged("LastCompleted");
					this.OnLastCompletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reset", DbType="DateTime")]
		public System.Nullable<System.DateTime> Reset
		{
			get
			{
				return this._Reset;
			}
			set
			{
				if ((this._Reset != value))
				{
					this.OnResetChanging(value);
					this.SendPropertyChanging();
					this._Reset = value;
					this.SendPropertyChanged("Reset");
					this.OnResetChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
